# Generated by Django 5.2.11 on 2026-03-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='md_file',
            field=models.FileField(blank=True, null=True, upload_to='md_uploads/'),
        ),
    ]
